openapi: 3.0.1
info:
  title: API_service
  description: API Definition of API_service
  version: 1.0.0
servers:
- url: http://localhost:8290/service
paths:
  /get:
    get:
      parameters:
      - name: id
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        default:
          description: Default response
  /create:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
